// Developer Express Code Central Example:
// How to display a chart within a range control using the numeric chart client
// 
// This example demonstrates how to set up a range control with the numeric chart
// client to display a chart with numeric data in the range control's background.
// 
// You can find sample updates and versions for different programming languages here:
// http://www.devexpress.com/example=E5110

// Developer Express Code Central Example:
// How to display a chart within a range control using the numeric chart client
// 
// This example demonstrates how to set up a range control with the numeric chart
// client to display a chart with numeric data in the range control's background.
// 
// You can find sample updates and versions for different programming languages here:
// http://www.devexpress.com/example=E5110

// Developer Express Code Central Example:
// How to display a chart within a range control using the numeric chart client
// 
// This example demonstrates how to set up a range control with the numeric chart
// client to display a chart with numeric data in the range control's background.
// 
// You can find sample updates and versions for different programming languages here:
// http://www.devexpress.com/example=E5110

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NumericRangeControlClient.Properties {


    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "11.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {

        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));

        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
    }
}
