' Developer Express Code Central Example:
' How to display a chart within a range control using the numeric chart client
' 
' This example demonstrates how to set up a range control with the numeric chart
' client to display a chart with numeric data in the range control's background.
' 
' You can find sample updates and versions for different programming languages here:
' http://www.devexpress.com/example=E5110

' Developer Express Code Central Example:
' How to display a chart within a range control using the numeric chart client
' 
' This example demonstrates how to set up a range control with the numeric chart
' client to display a chart with numeric data in the range control's background.
' 
' You can find sample updates and versions for different programming languages here:
' http://www.devexpress.com/example=E5110

' Developer Express Code Central Example:
' How to display a chart within a range control using the numeric chart client
' 
' This example demonstrates how to set up a range control with the numeric chart
' client to display a chart with numeric data in the range control's background.
' 
' You can find sample updates and versions for different programming languages here:
' http://www.devexpress.com/example=E5110

'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.18444
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------


Imports Microsoft.VisualBasic
Imports System
Namespace My


	<Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(), Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "11.0.0.0")> _
	Friend NotInheritable Partial Class Settings
		Inherits System.Configuration.ApplicationSettingsBase

		Private Shared defaultInstance As Settings = (CType(Global.System.Configuration.ApplicationSettingsBase.Synchronized(New Settings()), Settings))

		Public Shared ReadOnly Property [Default]() As Settings
			Get
				Return defaultInstance
			End Get
		End Property
	End Class
End Namespace
